const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  newSession: (size) => ipcRenderer.invoke('new-session', size),
  killSession: (id) => ipcRenderer.send('kill-session', { id }),
  sendInput: (id, data) => ipcRenderer.send('pty-input', { id, data }),
  resize: (id, cols, rows) => ipcRenderer.send('pty-resize', { id, cols, rows }),
  onPtyData: (cb) => ipcRenderer.on('pty-data', (_e, msg) => cb(msg)),
  onStatus: (cb) => ipcRenderer.on('status', (_e, msg) => cb(msg)),
  openFolder: () => ipcRenderer.invoke('open-folder'),
  gitStatus: () => ipcRenderer.invoke('git-status'),
  gitStage: (file) => ipcRenderer.invoke('git-stage', file),
  gitUnstage: (file) => ipcRenderer.invoke('git-unstage', file),
  gitDiff: (args) => ipcRenderer.invoke('git-diff', args),
  gitRevert: (args) => ipcRenderer.invoke('git-revert', args),
  gitCommit: (msg) => ipcRenderer.invoke('git-commit', msg),
  gitUndo: () => ipcRenderer.invoke('git-undo'),
  gitPush: () => ipcRenderer.invoke('git-push'),
  listDir: (rel) => ipcRenderer.invoke('list-dir', rel),
  readText: (file) => ipcRenderer.invoke('read-text', file),
  resolveLinkPath: (raw) => ipcRenderer.invoke('resolve-link-path', raw),
  openExternal: (target) => ipcRenderer.invoke('open-external', target),
  readAsset: (file) => ipcRenderer.invoke('read-asset', file),
  writeAsset: (file, base64) => ipcRenderer.invoke('write-asset', { file, base64 }),
  commitSession: (id) => ipcRenderer.invoke('commit-session', id),
  onSessionMeta: (cb) => ipcRenderer.on('session-meta', (_e, msg) => cb(msg)),
  onSessionName: (cb) => ipcRenderer.on('session-name', (_e, msg) => cb(msg)),
});
