const { ipcRenderer } = require('electron');

// The shared repo: folder picker + git porcelain for the git pane.
module.exports = {
  getRepoPath: () => ipcRenderer.invoke('get-repo-path'),
  openFolder: () => ipcRenderer.invoke('open-folder'),
  openFolderPath: (dir) => ipcRenderer.invoke('open-folder-path', dir),
  getRecentFolders: () => ipcRenderer.invoke('get-recent-folders'),
  removeRecentFolder: (dir) => ipcRenderer.invoke('remove-recent-folder', dir),
  removeRecentFolder: (dir) => ipcRenderer.invoke('remove-recent-folder', dir),
  onFolderChanged: (cb) => ipcRenderer.on('folder-changed', (_e, msg) => cb(msg)),
  setWindowTitle: (repoPath) => ipcRenderer.invoke('set-window-title', repoPath),
  gitIsRepo: () => ipcRenderer.invoke('git-is-repo'),
  createRepo: (opts) => ipcRenderer.invoke('create-repo', opts),
  gitStatus: () => ipcRenderer.invoke('git-status'),
  gitBranches: () => ipcRenderer.invoke('git-branches'),
  gitCheckout: (branch) => ipcRenderer.invoke('git-checkout', branch),
  gitCreateBranch: (branch) => ipcRenderer.invoke('git-create-branch', branch),
  gitDeleteBranch: (branch) => ipcRenderer.invoke('git-delete-branch', branch),
  gitStage: (file) => ipcRenderer.invoke('git-stage', file),
  gitUnstage: (file) => ipcRenderer.invoke('git-unstage', file),
  gitDiff: (args) => ipcRenderer.invoke('git-diff', args),
  gitRevert: (args) => ipcRenderer.invoke('git-revert', args),
  gitCommit: (msg) => ipcRenderer.invoke('git-commit', msg),
  gitUndo: () => ipcRenderer.invoke('git-undo'),
  gitPush: () => ipcRenderer.invoke('git-push'),
  gitStashList: () => ipcRenderer.invoke('git-stash-list'),
  gitStashPush: () => ipcRenderer.invoke('git-stash-push'),
  gitStashShow: (ref) => ipcRenderer.invoke('git-stash-show', ref),
  gitStashApply: (ref) => ipcRenderer.invoke('git-stash-apply', ref),
  gitStashPop: (ref) => ipcRenderer.invoke('git-stash-pop', ref),
  gitStashDrop: (ref) => ipcRenderer.invoke('git-stash-drop', ref),
  gitFetch: () => ipcRenderer.invoke('git-fetch'),
  gitPull: () => ipcRenderer.invoke('git-pull'),
  gitLog: () => ipcRenderer.invoke('git-log'),
  gitCommitDiff: (hash) => ipcRenderer.invoke('git-commit-diff', hash),
  gitRevertCommit: (hash) => ipcRenderer.invoke('git-revert-commit', hash),
  gitUndoCommit: (hash) => ipcRenderer.invoke('git-undo-commit', hash),
};
